spring.application.name=A06ServiceLayerApplication
spring.h2.console.enabled=true
spring.datasource.url = jdbc:h2:file:/Downloads/db
spring.datasource.username=omhpatil
spring.datasource.password=omhpatil
spring.jpa.hibernate.ddl-auto=create

#http://localhost:8080/h2-console       #URL TO CHEzCK DATABASE